name: emojis
description: Emojis for Dart! This package contain all unicode 13.0 emojis (2020)!
version: 0.9.0
author: Naji <teamnaji@gmail.com>
homepage:  https://github.com/i-Naji/emojis

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.10.0
